export const data = [
    {
        'id': '1',
        'institucion':'Instituto Salvadoreño de Formación Profesional (INSAFORP)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.994515,
        'longitud':-89.559086,
        'direccion':'Parque Industrial Santa Elena, Final Calle Siemens, Edificio INSAFORP, Antiguo Cuscatlán, La Libertad, El Salvador, C.A. PBX: (503) 2522 - 7300 ',
        'email':'crecimientopersonal@insaforp.org.sv',
        'URL':'https://www.insaforp.org.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '2',
        'institucion':'Centro de Entrenamiento y Desarrollo Empresarial (CEDE)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.692940,
        'longitud':-89.218191,
        'direccion':'Av. Franklin Delano Roosevelt #51 Av. Sur, Edif. 2707 San Salvador, El Salvador C.A',
        'email':'atencion.cliente@bandesal.gob.sv',
        'URL':'https://www.bandesal.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '3',
        'institucion':'Fundación Empresarial para el Desarrollo Educativo (FEPADE)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.482803,
        'longitud':-88.171396,
        'direccion':'Calle El Pedregal y calle de acceso a Escuela Militar, Antiguo Cuscatlán, La Libertad, El Salvador, Centroamérica',
        'email':'fepade@fepade.edu.sv',
        'URL':'https://fepade.org.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '4',
        'institucion':'Instituto Salvadoreño del Migrante ', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.489382,
        'longitud':-89.321165,
        'direccion':'Parque Industrial Santa Elena, Final Calle Siemens, Edificio INSAFORP, Antiguo Cuscatlán, La Libertad, El Salvador, C.A. PBX: (503) 2522 - 730041 Av Norte Nº 221 Col. Flor Blanca San Salvador, El Salvador, Centro América ',
        'email':'contacto@insami.foundation',
        'URL':'https://insami.foundation/jornada-navidena-de-ninos/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '5',
        'institucion':'Comité Internacional de Rescate (IRC)', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.716776,
        'longitud':-89.724144,
        'direccion':'',
        'email':'Communications@Rescue.org',
        'URL':'https://www.rescue.org/somos-irc',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Salvador',
    },
    {
        'id': '6',
        'institucion':'World Vision El Salvador', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.345160,
        'longitud':-88.435497,
        'direccion':'',
        'email':'cuentanos@wvi.org',
        'URL':'https://worldvision.org.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Salvador',
    },
    {
        'id': '7',
        'institucion':'Ciudad Mujer', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.921741,
        'longitud': -89.843114,
        'direccion':'',
        'email':'',
        'URL':'https://www.facebook.com/ciudadmujerSV/?locale=es_LA',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '8',
        'institucion':'Ministerio del Trabajo y Prevision (MINTRAB)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.036369,
        'longitud':-89.193931,
        'direccion':'Alameda Juan Pablo II y 17 Ave. Nte. Edificios 2 y 3, Centro de Gobierno, San Salvador, El Salvador',
        'email':'buzon.sugerencias@mtps.gob.sv',
        'URL':'https://www.mtps.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '9',
        'institucion':'Comision Nacional de la Micro y Pequeña Empresa (CONAMYPE)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud': 13.340129,
        'longitud':-87.839759,
        'direccion':'Alameda Manuel Enrique Araujo, Edificio CONAMYPE, Centro Comercial Plaza Suiza. ',
        'email':'https://api.whatsapp.com/send?phone=%2B50370747074&data=ARBk6xKK18Jep7-25EsvgW1hcw5Uz1aHP8iCWBoVZ__mOvXQcWs7XnIpk_sa9iDyaEgTbc5R_0FygUYXwSweAqmHFZba10u_BmVRGQMH5qoAOunQ92zleju4HcnHgP32iwUaWQZgAgNeV-DeCKfzGhE&source=FB_Page&app=facebook&entry_point=page_cta&fbclid=IwAR3ufSKhdcz17KYPPjp5l78skHoQr4eS390cDyZpCAKuCMzOGEQdhvR_bsk',
        'URL':'https://www.conamype.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '10',
        'institucion':'Ministerio de Economica', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.489261,
        'longitud':-88.416698,
        'direccion':'Alameda Juan Pablo II y Calle Guadalupe, Centro de Gobierno, Complejo Plan Maestro Edificio C-1 y C-2. San Salvador, El Salvador C.A.',
        'email':'informacion@economia.gob.sv',
        'URL':'https://www.economia.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '11',
        'institucion':'Banco de Fomento Agropecuario', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.815420,
        'longitud':-88.905066,
        'direccion':'Banco de Fomento Agropecuario, Kilómetro 10 ½ Carretera al Puerto de La Libertad, Santa Tecla, La Libertad, El Salvador',
        'email':'servicioalcliente@bfa.gob.sv',
        'URL':'https://www.bfa.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '12',
        'institucion':'Banco de Desarrollo de la Republica de El Salvador', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.641844,
        'longitud':-88.783542,
        'direccion':'Av. Franklin Delano Roosevelt #51 Av. Sur, Edif. 2707 San Salvador, El Salvador C.A.',
        'email':'atencion.cliente@bandesal.gob.sv',
        'URL':'https://www.bandesal.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '13',
        'institucion':'Fondo Solidario para la Familia Microempresaria', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.320908,
        'longitud':-87.862706,
        'direccion':'Prolongación Calle Arce, entre 39 y 41 Avenida Norte No. 2119, San Salvador, El Salvador',
        'email':'contactenos@fosofamilia.gob.sv',
        'URL':'https://www.fosofamilia.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '14',
        'institucion':'SAC Integral', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.098317,
        'longitud':-89.139040,
        'direccion':'Alameda Roosevelt y 47 Avenida Sur,Colonia Flor Blanca,San Salvador, El Salvador.',
        'email':'servicio.cliente@integral.com.sv',
        'URL':'https://www.integral.com.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '15',
        'institucion':'Instituto Nacional de la Juventud', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.479289,
        'longitud':-88.601013,
        'direccion':'Alameda Juan Pablo II y 17 Avenida Norte, Centro de Gobierno, Complejo Plan Maestro Edificio B-1 Segundo Nivel. San Salvador, El Salvador C.A ',
        'email':'info@injuve.gob.sv',
        'URL':'https://injuve.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '16',
        'institucion':'Ministerio de Agricultura y Ganaderia', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.995543,
        'longitud':-89.574888,
        'direccion':'Final 1a. Avenida Norte, 13 Calle Oriente y Av. Manuel Gallardo. Santa Tecla, La Libertad. República de El Salvador, C. A. ',
        'email':'info@mag.gob.sv',
        'URL':'https://www.mag.go.cr/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '17',
        'institucion':'Ministerio de Educacion', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.502602,
        'longitud':-89.295122,
        'direccion':'Alameda Juan Pablo II y calle Guadalupe , edificios A, San Salvador, El Salvador, Centro América',
        'email':'educacion@mined.gob.sv',
        'URL':'https://www.mined.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '18',
        'institucion':'Procuraduria General de la Republica', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.938540,
        'longitud':-89.027628,
        'direccion':'Oficinas Centrales Novena Calle Poniente y Trece Avenida Norte, Torre PGR Centro de Gobierno, San Salvador ',
        'email':'atencionalusuari@pgres.gob.sv',
        'URL':'https://www.pgr.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '19',
        'institucion':'Direccion General de Migracion y Extranjeria', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.337884,
        'longitud':-89.450713,
        'direccion':'9ª Calle Poniente y 15 Avenida Norte, Centro de Gobierno, San Salvador, El Salvador, Centroamérica ',
        'email':'atencion.usuarios@migracion.gob.sv',
        'URL':'https://www.migracion.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '20',
        'institucion':'Ministerio de Desarrollo Local', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.636176,
        'longitud':-88.520832,
        'direccion':'10°Ave. Sur y Calle México, frente a ex casa presidencial, Barrio San Jacinto, San Salvador',
        'email':'webmaster@mindel.gob.sv',
        'URL':'https://www.mindel.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '21',
        'institucion':'Fundación Guillermo Manuel Ungo (FundaUngo)', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.512361,
        'longitud':-88.863603,
        'direccion':'81 Avenida Norte y 7a. Calle Poniente, Casa No. 509. Colonia Escalón, San Salvador,El Salvador, C.A.',
        'email':'comunicaciones@fundaungo.org',
        'URL':'https://www.fundaungo.org.sv/programa-de-gobernabilidad-democratica',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Salvador',
    },
    {
        'id': '22',
        'institucion':'Registro Nacional de Personas Naturales(RNPN)', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.313885,
        'longitud':-88.588826,
        'direccion':'Alameda Manuel Enrique Araujo, kilometro 4 y 1/2 carretera a Santa Tecla, colonia Roma, pasaje Carbonell, San Salvador, El Salvador',
        'email':'info@rnpn.gob.sv',
        'URL':'https://www.rnpn.gob.sv/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '23',
        'institucion':'Instituto Técnico de Capacitación y Productividad (INTECAP)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.634915, 
        'longitud':-90.506882,
        'direccion':'Calle Doroteo Guamuch Flores 7-51 zona 5, Guatemala, C.A.',
        'email':'info@intecap.edu.gt',
        'URL':'https://intecap.edu.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '24',
        'institucion':'Fundacion para el Desarrollo Empresarial y Agricola (FUNDEA)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud': 14.558570,
        'longitud': -90.729523,
        'direccion':'15 avenida 2-09 zona 13, Guatemala City, Guatemala',
        'email':'solucionclientes@fundea.org.gt',
        'URL':'https://fundea.org.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '25',
        'institucion':'Instituto Guatemalteco de Migracion ', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.682860, 
        'longitud':-91.271383,
        'direccion':'6av. 3-11 zona 4 Ciudad de Guatemala',
        'email':'',
        'URL':'https://igm.gob.gt/category/atencion-y-proteccion-a-los-migrantes/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '26',
        'institucion':'Fundacion Fe y Alegria', 
        'categoria':'Asistencia Psico-social', 
        'latitud':17.222040,
        'longitud':-89.623882,
        'direccion':'12 Avenida 2-17 zona 1, Guatemala, CA.',
        'email':'fyaguatemala@feyalegria.org.gt',
        'URL':'https://www.feyalegria.org.gt/organizacion/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '27',
        'institucion':'Camara de Comercio Guatemalteca- Americana (AMCHAM Guatemala)', 
        'categoria':'Financiamiento (Creditos)', 
        'latitud':15.661399,
        'longitud':-88.895537,
        'direccion':' Europlaza Business Center 5ta. Avenida 5-55 Torre 1, Nivel 5 Oficina 502, Guatemala 01014 ',
        'email':'info@amchamguatemala.com',
        'URL':'https://amchamguate.com/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '28',
        'institucion':'Asociacion Guatemalteca de Profesionales de Gestion Humana (AGH)', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.833317, 
        'longitud':-91.515354,
        'direccion':'12 Calle 1-25, zona 10 Edificio Géminis 10, Torre Sur, nivel 5 oficina 507',
        'email':'',
        'URL':'https://www.agh.gt/site',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '29',
        'institucion':'Fundacion Habitat para la Humanidad', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.736717, 
        'longitud':-91.152900,
        'direccion':'Centro Comercial La Quinta 13-90, Calz. San Juan, Guatemala',
        'email':'guatecentro@habitatguate.org',
        'URL':'https://www.habitatguate.org/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '30',
        'institucion':'Fundacion Genesis', 
        'categoria':'Asistencia Psico-social', 
        'latitud':15.824999, 
        'longitud':-88.756232,
        'direccion':'8 calle 7-11 zona 9 Distrito Financiero, Guatemala C.A',
        'email':'genesis@genesisempresarial.com',
        'URL':'https://genesisempresarial.org/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '31',
        'institucion':'Asociacion de Retornados Guatemaltecos', 
        'categoria':'Asistencia Psico-social', 
        'latitud': 14.934167, 
        'longitud':-91.109722,
        'direccion':'15 calle D 7-58 Zona 13 Colonia Aurora I, Guatemala City, Guatemala',
        'email':'asoc.retornadosguatemaltecos@gmail.com',
        'URL':'https://www.facebook.com/Retornadosgt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '32',
        'institucion':'Casa Migrante de Guatemala', 
        'categoria':'Asistencia Psico-social', 
        'latitud':15.469206,
        'longitud':-90.364370,
        'direccion':'Guatemala, 15 Avenida "A"  01-94  Zona1 , Guatemala, 10001',
        'email':'cscalapm@gmail.com',
        'URL':'https://casadelmigrantegt.org/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '33',
        'institucion':'CentraRSE', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':15.724747,
        'longitud':-88.599292,
        'direccion':'',
        'email':'centrarse@centrarse.org',
        'URL':'https://centrarse.org/?gclid=Cj0KCQjw1rqkBhCTARIsAAHz7K1i8Hy1RWVeYWx_f76FsMiyCYNrEeGWjRICOHse0t8XpphtrlSPdVIaAscMEALw_wcB',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '34',
        'institucion':'COSEPSA RH', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.926945,
        'longitud':-90.778188,
        'direccion':'4a. calle 7-53 zona 9, Edificio Torre Azul Oficina 708, Guatemala City, Guatemala',
        'email':'rrhh@cosepsarh.com',
        'URL':'https://www.facebook.com/cosepsa',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '35',
        'institucion':'Te Conecta', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':15.285819, 
        'longitud':-89.038580,
        'direccion':'',
        'email':'info@teconecta.org.gt ',
        'URL':'https://www.teconecta.org.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '36',
        'institucion':'Asegua', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':15.319270,
        'longitud':-91.472910,
        'direccion':'',
        'email':'info@asegua.org ',
        'URL':'https://asegua.org/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '37',
        'institucion':'Ministerio de Relaciones Exteriores', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.567335,
        'longitud':-89.354790,
        'direccion':'',
        'email':'',
        'URL':'https://www.minex.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '38',
        'institucion':'Ministerio de Trabajo y Prevision Social', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.931849,
        'longitud':-90.825408,
        'direccion':'7 avenida 3-33 Zona 9 - Edificio Torre Empresarial',
        'email':'',
        'URL':'https://www.mintrabajo.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '39',
        'institucion':'Ministerio de Economia', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':15.405509, 
        'longitud':-91.149448,
        'direccion':'8a. Avenida 10-43 Zona 1 Ciudad de Guatemala Guatemala, CA',
        'email':'csmineco@mineco.gob.gt',
        'URL':'https://www.mineco.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '40',
        'institucion':'Ministerio de Educacion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.537759,
        'longitud':-91.685312,
        'direccion':'6a. Calle 1-87 Zona 10, 01010, Guatemala, C.A',
        'email':'',
        'URL':'https://www.mineduc.gob.gt/portal/index.asp',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '41',
        'institucion':'Ministerio de Gobernacion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.690261,
        'longitud':-91.270476,
        'direccion':'6a. Avenida 13-71, Zona 1, Guatemala City, Guatemala',
        'email':'',
        'URL':'https://mingob.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '42',
        'institucion':'Ministerio de Migracion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.286110, 
        'longitud':-89.901390,
        'direccion':'6av. 3-11 zona 4, Ciudad de Guatemala',
        'email':'',
        'URL':'https://igm.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '43',
        'institucion':'Municipalidad de Villanueva', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.973601,
        'longitud':-89.534897,
        'direccion':'5a. Avenida 4-55, Villa Nueva, Guatemala',
        'email':'https://api.whatsapp.com/send?text=Contacto%20https%3A%2F%2Fwww.villanueva.gob.gt%2Fcontacto%2F',
        'URL':'https://www.villanueva.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '44',
        'institucion':'Municipalidad de San Miguel Petapa', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':15.103610, 
        'longitud':-90.312940,
        'direccion':'1a. calle 1-56 zona 1, San Miguel Petapa, Guatemala',
        'email':'smp.comunicacionsocial@gmail.com',
        'URL':'https://munisanmiguelpetapa.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '45',
        'institucion':'Municipalidad de Mixco', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.772457,
        'longitud':-91.183615,
        'direccion':'4 Calle 4-98 Zona 1, Mixco, Guatemala',
        'email':'info@munimixco.gob.gt',
        'URL':'https://www.munimixco.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '46',
        'institucion':'Municipalidad de San Marcos', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.965571, 
        'longitud':-91.801396,
        'direccion':'7ma Avenida «A» 8-45 zona 1, San Marcos Guatemala, C.A.',
        'email':'uainfo@municipalidaddesanmarcos.gob.gt',
        'URL':'https://municipalidaddesanmarcos.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '47',
        'institucion':'Gobierno de la Republica de Guatemala', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':15.469206,
        'longitud':-90.364370,
        'direccion':'',
        'email':'',
        'URL':'https://guatemala.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '48',
        'institucion':'Fundacion Avina', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.930566, 
        'longitud':-90.816674,
        'direccion':'',
        'email':'',
        'URL':'https://www.avina.net/author/tatiana-lopezavina-net/page/3/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '49',
        'institucion':'IOM-OIM', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.661785,
        'longitud':-90.818800,
        'direccion':'Edificio Reforma 10, en la Avenida Reforma 09-55, zona 10. Ciudad de Guatemala, Guatemala',
        'email':'iomguatemala@iom.int',
        'URL':'https://nortedecentroamerica.iom.int/es/guatemala',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '50',
        'institucion':'Camara Guatemalteca de la Construccion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.568085,
        'longitud':-90.431140,
        'direccion':'Km. 8 Carretera a Muxbal, Santa Catarina Pinula.',
        'email':'info@construguate.com',
        'URL':'https://construguate.com/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '51',
        'institucion':'Municipalidad de Guatemala', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.530051,
        'longitud':-91.503349,
        'direccion':'21 Calle 6-77 Zona 1, Centro Cívico, Palacio Municipal. Ciudad de Guatemala, Guatemala, Centroamérica.',
        'email':'boletin@muniguate.com',
        'URL':'https://www.muniguate.com/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '52',
        'institucion':'Registro Nacional de las Personas', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.415298, 
        'longitud':-90.278102,
        'direccion':'Calzada Roosevelt 13-46 zona 7, Guatemala, Guatemala',
        'email':'contactenos@renap.gob.gt',
        'URL':'https://www.renap.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '53',
        'institucion':'Instituto Hondureño de Formacion Profesional (INFOP)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.0818,
        'longitud':-87.2068,
        'direccion':'',
        'email':'',
        'URL':'',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Honduras',
    },
    {
        'id': '54',
        'institucion':'Centro de Desarrollo Empresarial (CDE-MYPIME)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud':15.5049,
        'longitud':-88.0250,
        'direccion':'',
        'email':'',
        'URL':'',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '55',
        'institucion':'Centro de Atencion al Migrante Retorno (CAME)', 
        'categoria':'Asistencia Psico-social', 
        'latitud':16.3292,
        'longitud':-86.5180,
        'direccion':'',
        'email':'',
        'URL':'',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '56',
        'institucion':'Fundacion Alivio al Sufrimiento (FAS)', 
        'categoria':'Asistencia Psico-social', 
        'latitud':15.7597, 
        'longitud':-86.7811,
        'direccion':'',
        'email':'',
        'URL':'',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'ONG',
        'pais':'Honduras',
    },
   
]