export const data = [
    {
        'id': '1',
        'institucion':'Instituto Salvadoreño de Formación Profesional (INSAFORP)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.674215406227404, 
        'longitud':-89.25595526395726,
        'direccion':'Parque Industrial Santa Elena, Final Calle Siemens, Edificio INSAFORP, Antiguo Cuscatlán, La Libertad, El Salvador, C.A. PBX: (503) 2522 - 7300 ',
        'email':'crecimientopersonal@insaforp.org.sv',
        'URL':'https://www.insaforp.org.sv/',
        'contacto':'+503 252-27300',
        'descripcion':'El INSAFORP tiene como objeto satisfacer las necesidades de recursos humanos calificados que requiere el desarrollo económico y social del país y propiciar el mejoramiento de las condiciones de vida del trabajador y su grupo familiar.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '2',
        'institucion':'Centro de Entrenamiento y Desarrollo Empresarial (CEDE)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.702535956360478, 
        'longitud':-89.23664593327123,
        'direccion':'Av. Franklin Delano Roosevelt #51 Av. Sur, Edif. 2707 San Salvador, El Salvador C.A',
        'email':'atencion.cliente@bandesal.gob.sv',
        'URL':'https://www.bandesal.gob.sv/',
        'contacto':'+503 2592-1100',
        'descripcion':'El Banco de Desarrollo de la República de El Salvador, es una institución comprometida con el desarrollo económico y social del país, que brinda apoyo financiero y técnico a los sectores productivos para impulsar su crecimiento y competitividad, a través de una oferta oportuna, inclusiva y sostenible; debido a ese compromiso se define el Plan Estratégico Institucional 2023-2025, que tiene como propósito fortalecer y continuar desarrollando los pilares fundamentales que permitan un desempeño institucional eficiente, sostenible, transparente e innovador, y así ser referentes y uno de los principales aliados para el desarrollo del país.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '3',
        'institucion':'Fundación Empresarial para el Desarrollo Educativo (FEPADE)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.679431923535098,   
        'longitud':-89.25371554432701,
        'direccion':'Calle El Pedregal y calle de acceso a Escuela Militar, Antiguo Cuscatlán, La Libertad, El Salvador, Centroamérica',
        'email':'fepade@fepade.edu.sv',
        'URL':'https://fepade.org.sv/',
        'contacto':'+503 221-21600',
        'descripcion':'Somos una Fundación empresarial sin fines de lucro y sin afiliación política partidaria cuya misión es contribuir al desarrollo de la educación en El Salvador en todos sus niveles a través de la implementación efectiva de proyectos y programas.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '4',
        'institucion':'Instituto Salvadoreño del Migrante', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.701791975891892, 
        'longitud':-89.21241270889003,
        'direccion':'41 Av Norte Nº 221 Col. Flor Blanca San Salvador, El Salvador, Centro América. ',
        'email':'contacto@insami.foundation',
        'URL':'https://insami.foundation/jornada-navidena-de-ninos/',
        'contacto':'contacto@insami.foundation',
        'descripcion':'+503 220 72331',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '5',
        'institucion':'Comité Internacional de Rescate (IRC)', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.687215782768533,
        'longitud':-89.24169125724124,
        'direccion':'Av. La Capilla #411, San Salvador, El Salvador',
        'email':'Communications@Rescue.org',
        'URL':'https://www.rescue.org/somos-irc',
        'contacto':'-- no disponible --',
        'descripcion':'Hoy en día, el IRC y sus socios sirven a individuos y familias que necesitan ayuda y corren un mayor riesgo de desplazamiento. Apoyamos a los desplazados internos; Repatriados; y mujeres, niñas, jóvenes y miembros de la comunidad LGBTQ+ que son sobrevivientes de violencia de género.',
        'rubro':'ONG',
        'pais':'Salvador',
    },
    {
        'id': '6',
        'institucion':'World Vision El Salvador', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.60377866921786,
        'longitud':-89.2924281471226,
        'direccion':'Km. 16, Carretera a La Libertad, Complejo Corporativo Vía del Corso Tuscania, Zaragoza Zaragoza La Libertad CP, El Salvador',
        'email':'cuentanos@wvi.org',
        'URL':'https://worldvision.org.sv/',
        'contacto':'+503 226 19800',
        'descripcion':'Somos una organización cristiana internacional humanitaria que inició operaciones en El Salvador en 1975, con presencia en más de 100 países alrededor del mundo, dedicados a transformar las vidas de los más vulnerables: la niñez, sus familias y sus comunidades.',
        'rubro':'ONG',
        'pais':'Salvador',
    },
    {
        'id': '7',
        'institucion':'Ciudad Mujer Morazán', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.599195326341707, 
        'longitud':-88.0776781664746,
        'direccion':'RN 18E, El Rosario, SV El Salvador',
        'email':'webmaster@mindel.gob.sv',
        'URL':'https://www.facebook.com/ciudadmujerSV/?locale=es_LA',
        'contacto':'+503 2609 6400',
        'descripcion':'Es un programa impulsado por el Gobierno de El Salvador con el que se garantizan los derechos fundam',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '8',
        'institucion':'Ministerio del Trabajo y Prevision (MINTRAB)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.734549300600388, 
        'longitud':-89.31129458015006, 
        'direccion':'Alameda Juan Pablo II y 17 Ave. Nte. Edificios 2 y 3, Centro de Gobierno, San Salvador, El Salvador',
        'email':'buzon.sugerencias@mtps.gob.sv',
        'URL':'https://www.mtps.gob.sv/',
        'contacto':'+503 252-93700',
        'descripcion':'Somos la Institución rectora en la implementación de políticas públicas que fomentan el empleo decente, promueve el diálogo social, la defensa de los derechos laborales y la seguridad social, contando para ello con personal competente y comprometido en ofrecer servicios ágiles y de calidad para la ciudadanía.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '9',
        'institucion':'Comision Nacional de la Micro y Pequeña Empresa (CONAMYPE)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud': 13.694844216030456,
        'longitud':-89.230160169629,
        'direccion':'Alameda Manuel Enrique Araujo, Edificio CONAMYPE, Centro Comercial Plaza Suiza. ',
        'email':'abarberena@conamype.gob.sv',
        'URL':'https://www.conamype.gob.sv/',
        'contacto':'+503 259-29000',
        'descripcion':'Fomentar, proteger y desarrollar micro y pequeñas empresas protagonistas, fortaleciendo tanto su capacidad transformadora como su excelencia, para que se integren e incidan en el desarrollo económico nacional y territorial, de forma inclusiva, sostenible y justa.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '10',
        'institucion':'Ministerio de Economica', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.704479566058279, 
        'longitud':-89.20095528695757,
        'direccion':'Alameda Juan Pablo II y Calle Guadalupe, Centro de Gobierno, Complejo Plan Maestro Edificio C-1 y C-2. San Salvador, El Salvador C.A.',
        'email':'informacion@economia.gob.sv',
        'URL':'https://www.economia.gob.sv/',
        'contacto':'+503 259-05600',
        'descripcion':'Marcamos la ruta hacia el crecimiento para convertir a El Salvador en un economía próspera, dinámica, moderna, solidaria e inclusiva que mejore la calidad de vida de la población',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '11',
        'institucion':'Banco de Fomento Agropecuario', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.665396351255525,
        'longitud':-89.2748720768218,
        'direccion':'Kilómetro 10 ½ Carretera al Puerto de La Libertad, Santa Tecla, La Libertad, El Salvador',
        'email':'servicioalcliente@bfa.gob.sv',
        'URL':'https://www.bfa.gob.sv/',
        'contacto':'+503 224-10800',
        'descripcion':'Ser el referente nacional, innovador en las microfinanzas,fortaleciendo el desarrollo y progreso de los microempresarios, enforma sostenible.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '12',
        'institucion':'Banco de Desarrollo de la Republica de El Salvador', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.700273881940879,
        'longitud':-89.21717964014921,
        'direccion':'Av. Franklin Delano Roosevelt #51 Av. Sur, Edif. 2707 San Salvador, El Salvador C.A.',
        'email':'atencion.cliente@bandesal.gob.sv',
        'URL':'https://www.bandesal.gob.sv/',
        'contacto':'+503 259-21000',
        'descripcion':'El Banco de Desarrollo de la República de El Salvador, es una institución comprometida con el desarrollo económico y social del país, que brinda apoyo financiero y técnico a los sectores productivos para impulsar su crecimiento y competitividad',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '13',
        'institucion':'Fondo Solidario para la Familia Microempresaria', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.701060255477069, 
        'longitud':-89.21198635788508,
        'direccion':'Prolongación Calle Arce, entre 39 y 41 Avenida Norte No. 2119, San Salvador, El Salvador',
        'email':'contactenos@fosofamilia.gob.sv',
        'URL':'https://www.fosofamilia.gob.sv/',
        'contacto':'+503 259-11000',
        'descripcion':'',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '14',
        'institucion':'SAC Integral', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.70032739616336, 
        'longitud':-89.21548452092104, 
        'direccion':'Alameda Roosevelt y 47 Avenida Sur,Colonia Flor Blanca,San Salvador, El Salvador.',
        'email':'servicio.cliente@integral.com.sv',
        'URL':'https://www.integral.com.sv/',
        'contacto':'+503 2250-6090',
        'descripcion':'Institución dedicada a la microfinanzas con productos financieros especializados para PYME',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '15',
        'institucion':'Instituto Nacional de la Juventud', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.7043998170638, 
        'longitud':-89.19988047842222,
        'direccion':'Alameda Juan Pablo II y 17 Avenida Norte, Centro de Gobierno, Complejo Plan Maestro Edificio B-1 Segundo Nivel. San Salvador, El Salvador C.A ',
        'email':'info@injuve.gob.sv',
        'URL':'https://injuve.gob.sv/',
        'contacto':'+503 250-04150',
        'descripcion':'Somos la institución rectora que formula, dirige, ejecuta y vigila el cumplimiento de la Ley General de Juventud y la Política Nacional de Juventud en articulación con instituciones nacionales e internacionales para contribuir al desarrollo integral de la juventud',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '16',
        'institucion':'Ministerio de Agricultura y Ganaderia', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.683925689213769, 
        'longitud':-89.28665300516904,
        'direccion':'Final 1a. Avenida Norte, 13 Calle Oriente y Av. Manuel Gallardo. Santa Tecla, La Libertad. República de El Salvador, C. A. ',
        'email':'info@mag.gob.sv',
        'URL':'https://www.mag.go.cr/',
        'contacto':'+503 221-01700',
        'descripcion':'Somos la institución que formula y ejecuta políticas que promueven el desarrollo sustentable agrícola, pecuario, forestal, pesquero y acuícola, la seguridad y soberanía alimentaria; con enfoque de adaptación al cambio climático, a través de planes, programas y proyectos, brindando servicios de calidad para los actores del sector, con transparencia, inclusión y equidad para el buen vivir de las familias salvadoreñas.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '17',
        'institucion':'Ministerio de Educacion', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':13.704679278795314, 
        'longitud':-89.20086684125974,
        'direccion':'Alameda Juan Pablo II y calle Guadalupe , edificios A, San Salvador, El Salvador, Centro América',
        'email':'educacion@mined.gob.sv',
        'URL':'https://www.mined.gob.sv/',
        'contacto':'+503 259-22122',
        'descripcion':'Aprendizaje de calidad y significativo para la Primera Infancia',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '18',
        'institucion':'Procuraduria General de la Republica', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.704473384770939, 
        'longitud':-89.19739561925935,
        'direccion':'Oficinas Centrales Novena Calle Poniente y Trece Avenida Norte, Torre PGR Centro de Gobierno, San Salvador ',
        'email':'atencionalusuari@pgres.gob.sv',
        'URL':'https://www.pgr.gob.sv/',
        'contacto':'+503 223-19484',
        'descripcion':'Garantizar a las personas la defensa de sus derechos y el acceso a la justicia restaurativa, procurando la atención legal, psicosocial y resolución alterna de conflictos.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '19',
        'institucion':'Direccion General de Migracion y Extranjeria', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.704697425683975, 
        'longitud':-89.19796865015905,
        'direccion':'9ª Calle Poniente y 15 Avenida Norte, Centro de Gobierno, San Salvador, El Salvador, Centroamérica ',
        'email':'atencion.usuarios@migracion.gob.sv',
        'URL':'https://www.migracion.gob.sv/',
        'contacto':'+503 221-37700',
        'descripcion':'Controlar el ingreso y salida de nacionales y extranjeros; emitir documentos de viaje; registrar la permanencia de las personas extranjeras y el otorgamiento de calidades migratorias; apoyar la integración de las personas retornadas y la atención integral a los migrantes; detección de delitos de trata de personas y tráfico ilícito de migrantes contribuyendo a la seguridad pública y al desarrollo nacional.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '20',
        'institucion':'Ministerio de Desarrollo Local', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.68385374324312,
        'longitud': -89.19148246346656,
        'direccion':'10°Ave. Sur y Calle México, frente a ex casa presidencial, Barrio San Jacinto, San Salvador',
        'email':'webmaster@mindel.gob.sv',
        'URL':'https://www.mindel.gob.sv/',
        'contacto':'+503 213-31200',
        'descripcion':'El Ministerio de Desarrollo Local (MINDEL) tiene como misión mejorar la calidad de vida de las personas en los territorios de manera sostenible, con énfasis en las que viven en condición de vulnerabilidad, gestionando políticas, programas y proyectos en materia de desarrollo local sustentable.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '21',
        'institucion':'Fundación Guillermo Manuel Ungo (FundaUngo)', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.706750663109174, 
        'longitud':-89.23687608383457,
        'direccion':'81 Avenida Norte y 7a. Calle Poniente, Casa No. 509. Colonia Escalón, San Salvador,El Salvador, C.A.',
        'email':'comunicaciones@fundaungo.org',
        'URL':'https://www.fundaungo.org.sv/programa-de-gobernabilidad-democratica',
        'contacto':'+503 226-45130',
        'descripcion':'Es un centro de pensamiento dedicado a la generación de conocimientos y al fortalecimiento de las capacidades de los actores sociales y políticos para la promoción del desarrollo y la gobernabilidad democrática en El Salvador y Centroamérica. Las actividades que realiza buscan mejorar la calidad de vida de la población en un marco de participación y ampliación de las oportunidades económicas, sociales y políticas.',
        'rubro':'ONG',
        'pais':'Salvador',
    },
    {
        'id': '22',
        'institucion':'Registro Nacional de Personas Naturales(RNPN)', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.69710950015943,
        'longitud':-89.22671733733169,
        'direccion':'Alameda Manuel Enrique Araujo, kilometro 4 y 1/2 carretera a Santa Tecla, colonia Roma, pasaje Carbonell, San Salvador, El Salvador',
        'email':'info@rnpn.gob.sv',
        'URL':'https://www.rnpn.gob.sv/',
        'contacto':'+503 252-19300',
        'descripcion':'El Registro Nacional de las Personas Naturales es la entidad encargada de velar por la debida identificación de los salvadoreños por medio del Documento Único de Identidad (DUI).\nEl RNPN, es una entidad de derecho público, con autonomía en lo técnico y administrativo, para efectos presupuestarios adscrita al Tribunal Supremo Electoral.',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '23',
        'institucion':'Instituto Técnico de Capacitación y Productividad (INTECAP)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.317930962860268,  
        'longitud':-89.97355359284195,
        'direccion':'Km 110.4 Ruta Interamericana CA-01 Oriente, Aldea Amayito, Jutiapa.',
        'email':'centrojutiapa@intecap.edu.gt',
        'URL':'https://www.intecap.edu.gt/centros/centrojutiapa/',
        'contacto':'+502 779 37300 , 7793-7300',
        'descripcion':'El Centro de Capacitación JUTIAPA del INTECAP, tiene como objetivo contribuir al desarrollo económico y social de Guatemala creando las condiciones adecuadas para impulsar procesos de formación el Departamento de Jutiapa',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '24',
        'institucion':'Fundacion para el Desarrollo Empresarial y Agricola (FUNDEA)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud':14.59428550850677, 
        'longitud':-90.52010297858993,
        'direccion':'15 avenida 2-09 zona 13, Guatemala City, Guatemala',
        'email':'solucionclientes@fundea.org.gt',
        'URL':'https://fundea.org.gt/',
        'contacto':'+502 244 42222',
        'descripcion':'Fundación para el Desarrollo Empresarial y Agrícola FUNDEA Institución Guatemalteca de microfinanzas que gestiona servicios financieros con enfoque social y servicios de desarrollo empresarial.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '25',
        'institucion':'Instituto Guatemalteco de Migracion ', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.597713470933774, 
        'longitud':-90.52050176324653,
        'direccion':'6av. 3-11 zona 4 Ciudad de Guatemala',
        'email':'-----',
        'URL':'https://igm.gob.gt/category/atencion-y-proteccion-a-los-migrantes/',
        'contacto':'+502 2411-2411',
        'descripcion':'Velar por el respeto al derecho humano de migrar, garantizarlo mediante la administración adecuada del derecho migratorio y la asistencia y protección oportuna de aquellas personas migrantes extranjeras o nacionales que lo requieran.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '26',
        'institucion':'Fundacion Fe y Alegria', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.646109333097229, 
        'longitud':-90.50629999208137,
        'direccion':'12 Avenida 2-17 zona 1, Guatemala, CA.',
        'email':'fyaguatemala@feyalegria.org.gt',
        'URL':'https://www.feyalegria.org.gt/organizacion/',
        'contacto':'+502 232 40000',
        'descripcion':'Somos un Movimiento Internacional de Educación Popular Integral y Promoción Social, dirigido a sectores empobrecidos y excluidos de la sociedad, para potenciar su desarrollo personal y participación social. ',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '27',
        'institucion':'Camara de Comercio Guatemalteca- Americana (AMCHAM Guatemala)', 
        'categoria':'Financiamiento (Creditos)', 
        'latitud':14.58771817317047,
        'longitud':-90.51390043996327,
        'direccion':' Europlaza Business Center 5ta. Avenida 5-55 Torre 1, Nivel 5 Oficina 502, Guatemala 01014 ',
        'email':'info@amchamguatemala.com',
        'URL':'https://amchamguate.com/',
        'contacto':'+502 241 70800',
        'descripcion':'Promover Relaciones comerciales entre Guatemala y Estados Unidos, por medio del fortalecimiento de la actividad económica y de la libre empresa, y llevar más lejos los intereses legítimos de sus miembros, fomentando la responsabilidad social.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '28',
        'institucion':'Asociacion Guatemalteca de Profesionales de Gestion Humana (AGH)', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.65958575904457,  
        'longitud':-90.51560610742439,
        'direccion':'12 Calle 1-25, zona 10 Edificio Géminis 10, Torre Sur, nivel 5 oficina 507',
        'email':'cm@agh.gt',
        'URL':'https://www.agh.gt/site',
        'contacto':'(502)2269-2781',
        'descripcion':'Somos un equipo de profesionales responsables de la administración, consultoría o investigación relacionada a la gestión humana de diferentes empresas e instituciones de Guatemala.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '29',
        'institucion':'Fundacion Habitat para la Humanidad', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.85292373351294,  
        'longitud':-91.53648400556955,
        'direccion':'Centro Comercial La Quinta 13-90, Calz. San Juan, Guatemala',
        'email':'guatecentro@habitatguate.org',
        'URL':'https://www.habitatguate.org/',
        'contacto':'+502 793 13131',
        'descripcion':'Somos una organización sin fines de lucro, que trabaja para mejorar la calidad de vida de las familias guatemaltecas por medio de viviendas nuevas, mejoradas y Kit Saludable (Estufa mejorada, filtro de agua y letrina).',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '30',
        'institucion':'Fundacion Genesis', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.600486268575715,  
        'longitud':-90.52164037673901,
        'direccion':'8 calle 7-11 zona 9 Distrito Financiero, Guatemala C.A',
        'email':'genesis@genesisempresarial.com',
        'URL':'https://genesisempresarial.org/',
        'contacto':'+502 2388-9100',
        'descripcion':'Somos una fundación guatemalteca especializada en desarrollo económico y social, no lucrativa, sin fines políticos ni religiosos, que para alcanzar sus objetivos de desarrollo sostenido combina su amplia experiencia en microfinanzas y servicios de desarrollo empresarial con un enfoque social, basado en la capacitación constante y la promoción del desarrollo individual y comunitario.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '31',
        'institucion':'Asociacion de Retornados Guatemaltecos', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.584641831425404,
        'longitud':-90.53286237673936, 
        'direccion':'15 calle D 7-58 Zona 13 Colonia Aurora I, Guatemala City, Guatemala',
        'email':'asoc.retornadosguatemaltecos@gmail.com',
        'URL':'https://www.facebook.com/Retornadosgt/',
        'contacto':'+502 2294 9217',
        'descripcion':'Brindamos atención primaria personalizada en el arribo y post arribo a personas migrantes retornadas',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '32',
        'institucion':'Casa Migrante de Guatemala', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.651644965368881,
        'longitud':-90.50080061273864,
        'direccion':'Guatemala, 15 Avenida "A"  01-94  Zona1 , Guatemala, 10001',
        'email':'cscalapm@gmail.com',
        'URL':'https://casadelmigrantegt.org/',
        'contacto':'+502 223 02781',
        'descripcion':'Los Misioneros de San Carlos Scalabrinianos hemos empezado en 1985 el ministerio de la acogida y de la hospitalidad hacia todo tipo de migrante, deportados y refugiados abriendo la primera Casa del Migrante en Tijuana, Baja California. Continuo en Ciudad de Juárez, luego en Tecún Umán, frontera Guatemala-México , Tapachula, y en la Capital de Guatemala, en Guatemala.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '33',
        'institucion':'CentraRSE', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':15.865470908773917, 
        'longitud':-90.38414656363696,
        'direccion':'-------no disponible -------',
        'email':'centrarse@centrarse.org',
        'URL':'https://centrarse.org/?gclid=Cj0KCQjw1rqkBhCTARIsAAHz7K1i8Hy1RWVeYWx_f76FsMiyCYNrEeGWjRICOHse0t8XpphtrlSPdVIaAscMEALw_wcB',
        'contacto':'+(502) 2268-3700 / 5066-4270',
        'descripcion':'Fundada en el año 2003, CentraRSE es hoy una organización que cuenta con más de 100 empresas asociadas que pertenecen a más de 20 sectores y subsectores productivos del país y dan empleo a 150,000 familias; convirtiéndose en la coalición de empresas promotoras de la RSE más influyente del país y una de las más importantes a nivel regional.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '34',
        'institucion':'COSEPSA RH', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.61061246856556, 
        'longitud':-90.51626240742542,
        'direccion':'4a. calle 7-53 zona 9, Edificio Torre Azul Oficina 708, Guatemala City, Guatemala',
        'email':'rrhh@cosepsarh.com',
        'URL':'https://www.facebook.com/cosepsa',
        'contacto':'+502 2361 0265',
        'descripcion':'Empresa comprometida en brindarle un servicio de primera.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '35',
        'institucion':'Te Conecta', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.610536850509927,  
        'longitud':-90.50046211906715,
        'direccion':'JF6X+5R6, 10A Avenida A, Cdad. de Guatemala, Guatemala',
        'email':'info@teconecta.org.gt ',
        'URL':'https://www.teconecta.org.gt/',
        'contacto':'+502 3266-4900',
        'descripcion':'Desarrollamos y operamos sistemas de transporte de energía, basándonos en prácticas éticas, rentables,sostenibles y competitivas, con los más altos estándares de calidad, conocimiento y tecnología.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '36',
        'institucion':'Asegua', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.580108219319758,
        'longitud':-90.52426132091855,
        'direccion':'HFHG+W8F, 18 Calle, Cdad. de Guatemala, Guatemala',
        'email':'info@asegua.org ',
        'URL':'https://asegua.org/',
        'contacto':'+502 221 09377',
        'descripcion':'Creemos en el poder que se genera al unirnos, somos un grupo de emprendedores que creemos que juntos podemos crear mejores ecosistemas para el desarrollo de negocios.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '37',
        'institucion':'Ministerio de Relaciones Exteriores', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.60966833298693,
        'longitud':-90.5137305613955,
        'direccion':'4-17, 2A Avenida 10, Cdad. de Guatemala, Guatemala',
        'email':'--------',
        'URL':'https://www.minex.gob.gt/',
        'contacto':'(502) 2410-0000',
        'descripcion':' (502) 2410-0000',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '38',
        'institucion':'Ministerio de Trabajo y Prevision Social', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.730625028956739, 
        'longitud':-90.5908120632207,
        'direccion':'7 avenida 3-33 Zona 9 - Edificio Torre Empresarial',
        'email':'---------',
        'URL':'https://www.mintrabajo.gob.gt/',
        'contacto':'+502 242 22500',
        'descripcion':'Movilidad Laboral por una migración regular, ordenada y segura',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '39',
        'institucion':'Ministerio de Economia', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.638838565224631,
        'longitud':-90.51172209226448, 
        'direccion':'8a. Avenida 10-43 Zona 1 Ciudad de Guatemala Guatemala, CA',
        'email':'csmineco@mineco.gob.gt',
        'URL':'https://www.mineco.gob.gt/',
        'contacto':'+(502) 2412-0200',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '40',
        'institucion':'Ministerio de Educacion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.608592705726993,
        'longitud':-90.51376756139551,
        'direccion':'6a. Calle 1-87 Zona 10, 01010, Guatemala, C.A',
        'email':'-----------',
        'URL':'https://www.mineduc.gob.gt/portal/index.asp',
        'contacto':'+502 241 19595',
        'descripcion':'Somos una institución evolutiva, organizada, eficiente y eficaz, generadora de oportunidades de enseñanza-aprendizaje, orientada a resultados, que aprovecha diligentemente las oportunidades que el siglo XXI le brinda y comprometida con una Guatemala mejor.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '41',
        'institucion':'Ministerio de Gobernacion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.635392461772996,
        'longitud':-90.51456141906662,
        'direccion':'6a. Avenida 13-71, Zona 1, Guatemala City, Guatemala',
        'email':'--------------',
        'URL':'https://mingob.gob.gt/',
        'contacto':'+502 241 38888',
        'descripcion':'',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '42',
        'institucion':'Ministerio de Migracion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.621261655642536, 
        'longitud':-90.51659241366855,
        'direccion':'6av. 3-11 zona 4, Ciudad de Guatemala',
        'email':'----------',
        'URL':'https://igm.gob.gt/',
        'contacto':'+502 241 12411',
        'descripcion':'Velar por el respeto al derecho humano de migrar, garantizarlo mediante la administración adecuada del derecho migratorio y la asistencia y protección oportuna de aquellas personas migrantes extranjeras o nacionales que lo requieran.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '43',
        'institucion':'Municipalidad de Villanueva', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.973601,
        'longitud':-89.534897,
        'direccion':'5a. Avenida 4-55, Villa Nueva, Guatemala',
        'email':'https://api.whatsapp.com/send?text=Contacto%20https%3A%2F%2Fwww.villanueva.gob.gt%2Fcontacto%2F',
        'URL':'https://www.villanueva.gob.gt/',
        'contacto':'Bruce Wayne',
        'descripcion':'Bruce Wayne',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '44',
        'institucion':'Municipalidad de San Miguel Petapa', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.52586176010338, 
        'longitud':-90.58877447674054,
        'direccion':'1a. calle 1-56 zona 1, San Miguel Petapa, Guatemala',
        'email':'smp.comunicacionsocial@gmail.com',
        'URL':'https://munisanmiguelpetapa.gob.gt/',
        'contacto':'------------',
        'descripcion':'',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
     {
        'id': '45',
        'institucion':'Municipalidad de Mixco', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.63139923042114, 
        'longitud':-90.60568555769348,
        'direccion':'4 Calle 4-98 Zona 1, Mixco, Guatemala',
        'email':'info@munimixco.gob.gt',
        'URL':'https://www.munimixco.gob.gt/',
        'contacto':'+502 230 77300',
        'descripcion':'',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '46',
        'institucion':'Municipalidad de San Marcos', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.969417793468825,  
        'longitud':-91.79005969153958,
        'direccion':'7ma Avenida «A» 8-45 zona 1, San Marcos Guatemala, C.A.',
        'email':'uainfo@municipalidaddesanmarcos.gob.gt',
        'URL':'https://municipalidaddesanmarcos.gob.gt/',
        'contacto':'+502 795 78787',
        'descripcion':'Institución, respetable, fuerte, moderna y transparente, con liderazgo y capacidad de gestión, que presta bienes y servicios de calidad para que todos los habitantes de la Cabecera del departamento de San Marcos alcancen su bienestar y realicen sus más altas aspiraciones.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '47',
        'institucion':'Gobierno de la Republica de Guatemala', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.643977585283935, 
        'longitud':-90.51285155248807,
        'direccion':'A, 6A Avenida 4-18, Cdad. de Guatemala, Guatemala',
        'email':'udip@saas.gob.gt',
        'URL':'https://guatemala.gob.gt/',
        'contacto':'+502 232 76000',
        'descripcion':'',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '48',
        'institucion':'Fundacion Avina', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.930566, 
        'longitud':-90.816674,
        'direccion':'',
        'email':'',
        'URL':'https://www.avina.net/author/tatiana-lopezavina-net/page/3/',
        'contacto':'',
        'descripcion':'',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '49',
        'institucion':'IOM-OIM', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.60878921308125, 
        'longitud':-90.51537336765608,
        'direccion':'Edificio Reforma 10, en la Avenida Reforma 09-55, zona 10. Ciudad de Guatemala, Guatemala',
        'email':'iomguatemala@iom.int',
        'URL':'https://nortedecentroamerica.iom.int/es/guatemala',
        'contacto':'+502 230 53000',
        'descripcion':'La organización cuenta con áreas de acción prioritarias que tienen como ejes transversales la defensa y promoción de los derechos humanos de las poblaciones migrantes, la inclusión de las poblaciones diversas, el mantenimiento de la diversidad cultural y lingüística, y alentar la igualdad de género.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '50',
        'institucion':'Camara Guatemalteca de la Construccion', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.565830502101658,
        'longitud':-90.48139532091885,
        'direccion':'Km. 8 Carretera a Muxbal, Santa Catarina Pinula.',
        'email':'info@construguate.com',
        'URL':'https://construguate.com/',
        'contacto':'+502 238 72727',
        'descripcion':'La Cámara Guatemalteca de la Construcción, es la entidad representativa del Sector Construcción de Guatemala a nivel nacional y regional. Es una asociación civil, apolítica y no lucrativa que, desde 1971, agremia a las empresas más importantes del Sector Construcción.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '51',
        'institucion':'Municipalidad de Guatemala', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.62754673767182,
        'longitud':-90.51544530557425,
        'direccion':'21 Calle 6-77 Zona 1, Centro Cívico, Palacio Municipal. Ciudad de Guatemala, Guatemala, Centroamérica.',
        'email':'boletin@muniguate.com',
        'URL':'https://www.muniguate.com/',
        'contacto':'+502 2285-8000',
        'descripcion':'',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '52',
        'institucion':'Registro Nacional de las Personas', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.626290943862776, 
        'longitud':-90.5494362640092,  
        'direccion':'Calzada Roosevelt 13-46 zona 7, Guatemala, Guatemala',
        'email':'contactenos@renap.gob.gt',
        'URL':'https://www.renap.gob.gt/',
        'contacto':'+502 241 61900',
        'descripcion':'RENAP es la entidad encargada de organizar y mantener el registro único de identificación de las personas naturales, inscribir los hechos y actos relativos a su estado civil, capacidad civil y demás datos de identificación desde su nacimiento hasta su muerte, así como la emisión del Documento Personal de Identificación.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '53',
        'institucion':'Instituto Hondureño de Formacion Profesional (INFOP-San pedro sula)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':15.480473755883505,
        'longitud':-88.0264063839295, 
        'direccion':'Zona el Cacao, 35 calle, 3ra. Avenida, sureste 5 cuadras después de la Toyota.',
        'email':'https://www.facebook.com/infopRNO/',
        'URL':'http://infop.hn/',
        'contacto':'+504 2556-7930',
        'descripcion':'Intituto de Formación Profesional - Capacitando a miles de Hondureños para Una Vida Mejor...',
        'rubro':'PUBLICO',
        'pais':'Honduras',
    },
    {
        'id': '54',
        'institucion':'Centro de Desarrollo Empresarial (CDE MIPYME valle de sula)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud':15.603906233223253, 
        'longitud':-87.98844802864814,
        'direccion':'Barrio Paz Barahona, 9 Avenida, 12 y, 13 Calle SE, San Pedro Sula 21101',
        'email':'comunicaciones@cdevs.org',
        'URL':'https://cdevs.org/?fbclid=IwAR22zqSpc4waaRDXN_EhGpHcKq-SGSU8QYts4TBlbFLrsUvTYXgpc02ESGw',
        'contacto':'9581-8453',
        'descripcion':'Organización de desarrollo económico siendo nuestro propósito el fortalecimiento la economía del país',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    
    {
        'id': '55',
        'institucion':'CAMR - Centro de Atención al Migrante Retornado (Oficinas) CAMR ', 
        'categoria':'Asistencia Psico-social', 
        'latitud':15.737476671531624, 
        'longitud':-88.07987616345991,
        'direccion':'antigua terminal del Aeropuerto Ramon Villeda Morales , San Pedro Sula, Honduras',
        'email':'asesoriacamr@hotmail.com',
        'URL':'https://conmigho.hn/centro-de-atencion-al-migrante-retornado-sps/',
        'contacto':'+504 223 60200',
        'descripcion':'Brindar asistencia inmediata a las personas Deportadas de Estados Unidos de Norte América',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '56',
        'institucion':'Fundacion Alivio al Sufrimiento (FAS)', 
        'categoria':'Asistencia Psico-social', 
        'latitud':13.865246027245606, 
        'longitud':-86.5623294193324,
        'direccion':'Barrio San José, edificio Hospital Alivio del Sufrimiento,El Paraíso, El Paraíso, Honduras, C.A.',
        'email':'funadsu@gmail.com',
        'URL':'https://fundacionaliviohn.org',
        'contacto':'(504) 9800-0025',
        'descripcion':'El objetivo principal de la Fundación es contribuir al desarrollo integral de Honduras a través de la caridad brindando protección, cobijo y amparo a los más desposeídos y personas de escasos recursos económicos que no tengan acceso a servicios para atender su salud, educación y vivienda.',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '57',
        'institucion':'Centro de Desarrollo Empresarial (CDE MIPYME SANTA BARBARA)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud':15.207337407212076,
        'longitud':-88.17558303977495,
        'direccion':'Edificio AHPROCAFE, Barrio Llano del Conejo, Santa Bárbara',
        'email':'cdesantabarbarahn@yahoo.com',
        'URL':'https://www.facebook.com/cdemipymesb.hn',
        'contacto':'2643-2200',
        'descripcion':'El Centro de Desarrollo Empresarial CDE MIPYME Región Santa Bárbara, facilita acompañamiento empresarial',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '58',
        'institucion':'Centro de Desarrollo Empresarial (CDE MIPYME REGIÓN OCCIDENTE)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud':15.027033112258342, 
        'longitud':-88.75785840946729,
        'direccion':'Sector la Cuchilla frente a, Barrio Santa Teresa, Santa Rosa de Copán, la represa, Santa Rosa de Copán',
        'email':'info@cdemipymeroc.org',
        'URL':'http://www.cdemipymeroc.org/?fbclid=IwAR0ToKbOaDrGX0K8GiVem-zAwOvI7grc9p1t36m56qszpzSs96y3eO7qaGM',
        'contacto':'+504 32636185',
        'descripcion':'ninguna',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '59',
        'institucion':'Centro de Desarrollo Empresarial (CDE MIPYME Ocotepeque)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud':14.527756488291827,
        'longitud':-89.20829784639909,
        'direccion':'Frente a represa de agua, Barrio Santa Teresa, sector La Cuchilla, Santa Rosa de Copán',
        'email':'info@cdemipymeroc.org',
        'URL':'https://cdemipymeroc.org/contacto.html',
        'contacto':'+(504) 2662-0286',
        'descripcion':'Elaboración de diagnósticos, Plan de Negocios, Capacitaciones, Asesorías & Acompañamientos',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '60',
        'institucion':'Centro de Desarrollo Empresarial (CDE MIPYME LEMPIRA)', 
        'categoria':'Emprendimiento Empresarial (Formalizacion legal y marketing)', 
        'latitud':14.517121178964025, 
        'longitud':-89.18632519093902,
        'direccion':'Edificio de AHPROCAFE, Gracias',
        'email':'info@cdemipymeroc.org',
        'URL':'http://www.cdemipymeroc.org/?fbclid=IwAR0RnB1zIBkATDiTgvrW5_Fx4dK_37pt5ODA8nUDLNkv5QPUrP0SwCqoF-s',
        'contacto':'967-23072',
        'descripcion':'Elaboración de diagnósticos, Plan de Negocios, Capacitaciones, Asesorías & Acompañamientos',
        'rubro':'ONG',
        'pais':'Honduras',
    },
    {
        'id': '61',
        'institucion':'Instituto Hondureño de Formacion Profesional (INFOP-Tegucigalpa)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.074860404209058, 
        'longitud':-87.1824814584797, 
        'direccion':'Bulevard Centroamérica, frente a Col. Miraflores., Tegucigalpa, Honduras',
        'email':'annieturcios@infop.hn',
        'URL':'http://www.infopvirtual.net/',
        'contacto':'+504 2230-4208',
        'descripcion':'Intituto de Formación Profesional - Capacitando a miles de Hondureños para Una Vida Mejor...',
        'rubro':'PUBLICO',
        'pais':'Honduras',
    },
    {
        'id': '62',
        'institucion':'Instituto Nacional de Migración', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.08864128424977,  
        'longitud':-87.18874221932694, 
        'direccion':'Centro Cívico Gubernamental, Edificio B, Piso 1 Blvd. Juan Pablo Segundo, Diag. Republica de Corea, Tegucigalpa',
        'email':'callcenter@inm.gob.hn',
        'URL':'https://inm.gob.hn/index.html',
        'contacto':'+504 223-27800',
        'descripcion':'Instituto Nacional de Migración tiene como misión fundamental ejercer el control y regulación como máxima autoridad en materia migratoria a nacionales y extranjeros en el marco de la protección de sus derechos y seguridad, en aplicación de la Ley de Migración y Extranjería y la Política Migratoria del Gobierno de la República, mediante una gestión migratoria moderna, dinámica y transparente.',
        'rubro':'PUBLICO',
        'pais':'Honduras',
    },
    {
        'id': '63',
        'institucion':'Instituto de Derechos Humanos de la UCA', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':13.679728129557535,
        'longitud': -89.23603906141409,
        'direccion':'Bulevar Los Próceres, Antiguo Cuscatlán, La Libertad, El salvador',
        'email':'idh.comu1@uca.edu.sv',
        'URL':'https://www.uca.edu.sv/idhuca/',
        'contacto':'+503 221-06678',
        'descripcion':'En la búsqueda del cumplimiento de la justicia y respeto de los derechos humanos de la sociedad salvadoreña, la promoción de la participación ciudadana y el fortalecimiento institucional',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '64',
        'institucion':'Ciudad Mujer - San Miguel', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.482033935716261, 
        'longitud':-88.17739041006608, 
        'direccion':'Antiguo FENALDESAL, 15° calle Oriente, entre 10° y 8° Avenida Sur. Municipio de San Miguel.',
        'email':'mwembesg@ciudadmujer.gob.sv',
        'URL':'https://juntasdenorteasur.com/listing/ciudad-mujer-san-miguel/',
        'contacto':'+503 768 34560 , 2609-2000',
        'descripcion':'Sensibilización / información, Capacitación / educación, Fortalecimiento comunitario',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '65',
        'institucion':'Ciudad Mujer - Usulután', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.482033935716261, 
        'longitud':-88.17739041006608, 
        'direccion':'Centro de Gobierno, 9a.calle oriente y final 8a. Avenida sur, Barrios el Calvario, frente al, 9a Calle Ote., Usulután, El Salvador',
        'email':'maparicio@ciudadmujer.gob.sv',
        'URL':'https://elsalvador.cuentanos.org/es/articles/8645035788829',
        'contacto':'+503 2609-1200',
        'descripcion':'Sensibilización / información, Capacitación / educación, Fortalecimiento comunitario',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '66',
        'institucion':'Ciudad Mujer - Sede Lourdes Colón', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.78523669967114,    
        'longitud':-89.41652299215782,
        'direccion':'kilómetro 29 1/2 Carretera a Sonsonate, calle desvío a las 600, Cantón Entre Ríos, Colón, departamento de la Libertad',
        'email':'bromero@ciudadmujer.gob.sv',
        'URL':'',
        'contacto':'+503 2565-0800',
        'descripcion':'Sensibilización / información, Capacitación / educación, Fortalecimiento comunitario',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '67',
        'institucion':'Ciudad Mujer - Sede Santa Ana', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.958973835187598,     
        'longitud':-89.58151290291956,
        'direccion':'Ciudad Mujer Santa Ana, km. 61 ½ carretera Panamericana, finca Santa Teresa, Cantón Chupadero, Santa Ana, El Salvador',
        'email':'rcenteno@ciudadmujer.gob.sv',
        'URL':'https://www.facebook.com/ciudadmujerSV/posts/2375990912452903/',
        'contacto':'+503 240 42500',
        'descripcion':'Sensibilización / información, Capacitación / educación, Fortalecimiento comunitario',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '68',
        'institucion':'Ciudad Mujer- San Martín', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.762238809493752,     
        'longitud':-89.05873750411467,
        'direccion':'Finca Gran Bretaña, Kilómetro 16 1/2 Carretera de Oro, Municipio de San Martín, Departamento de San Salvador, Autop. de Oro, San Salvador, El Salvador',
        'email':'',
        'URL':'https://www.facebook.com/ciudadmujerSV/posts/2295472860504709/?locale=es_LA',
        'contacto':'+503 255 51400',
        'descripcion':'Sensibilización / información, Capacitación / educación, Fortalecimiento comunitario',
        'rubro':'PUBLICO',
        'pais':'Salvador',
    },
    {
        'id': '69',
        'institucion':'World Vision El Salvador', 
        'categoria':'Atencion Psico-social', 
        'latitud':13.631807052622582, 
        'longitud':-89.28487504670031,
        'direccion':'El Barillo, El Salvador',
        'email':'cuentanos@wvi.org',
        'URL':'https://worldvision.org.sv/',
        'contacto':'+503 226 19800',
        'descripcion':'Somos una organización cristiana internacional humanitaria que inició operaciones en El Salvador en 1975, con presencia en más de 100 países alrededor del mundo, dedicados a transformar las vidas de los más vulnerables: la niñez, sus familias y sus comunidades.',
        'rubro':'ONG',
        'pais':'Salvador',
    },
    {
        'id': '70',
        'institucion':'Instituto Técnico de Capacitación y Productividad (INTECAP)', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.748416638285883,   
        'longitud':-90.49356227118432,
        'direccion':'Mateo Flores 7-51, Calle del Estadio, Cdad. de Guatemala 01005, Guatemala',
        'email':'centrojutiapa@intecap.edu.gt',
        'URL':'https://www.intecap.edu.gt/centros/centrojutiapa/',
        'contacto':'+502 241 05555',
        'descripcion':'El Centro de Capacitación JUTIAPA del INTECAP, tiene como objetivo contribuir al desarrollo económico y social de Guatemala creando las condiciones adecuadas para impulsar procesos de formación el Departamento de Jutiapa',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '71',
        'institucion':'Instituto Técnico de Capacitación y Productividad (INTECAP)- Coatepeque', 
        'categoria':'Entrenamiento Tecnico (Habilidades Laborales)', 
        'latitud':14.940804316033296,    
        'longitud':-91.87169634198818,
        'direccion':'P428+Q7W, CA2, Coatepeque, Guatemala',
        'email':'centrojutiapa@intecap.edu.gt',
        'URL':'https://www.intecap.edu.gt/centros/centrojutiapa/',
        'contacto':'+502 777 56262',
        'descripcion':'El Centro de Capacitación JUTIAPA del INTECAP, tiene como objetivo contribuir al desarrollo económico y social de Guatemala creando las condiciones adecuadas para impulsar procesos de formación el Departamento de Jutiapa',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '72',
        'institucion':'Casa Migrante de Guatemala', 
        'categoria':'Asistencia Psico-social', 
        'latitud':14.611450113000606, 
        'longitud':-90.5042338402033,
        'direccion':'15 Avenida 1-94, Cdad. de Guatemala, Guatemala',
        'email':'cscalapm@gmail.com',
        'URL':'https://casadelmigrantegt.org/',
        'contacto':'+502 223 02781',
        'descripcion':'Los Misioneros de San Carlos Scalabrinianos hemos empezado en 1985 el ministerio de la acogida y de la hospitalidad hacia todo tipo de migrante, deportados y refugiados abriendo la primera Casa del Migrante en Tijuana, Baja California. Continuo en Ciudad de Juárez, luego en Tecún Umán, frontera Guatemala-México , Tapachula, y en la Capital de Guatemala, en Guatemala.',
        'rubro':'ONG',
        'pais':'Guatemala',
    },
    {
        'id': '73',
        'institucion':'Bufete Popular de la Universidad Rafael Landívar', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.636894122753851,  
        'longitud':-90.51802110149107,
        'direccion':'Ciudad de Guatemala, 13 calle 2-73, zona 1',
        'email':'bufetepopular@url.edu.gt',
        'URL':'https://principal.url.edu.gt/acerca-de/servicios/bufete-popular/',
        'contacto':'+502 242 62626',
        'descripcion':'El Bufete Popular de la Universidad Rafael Landívar es el centro de prácticas y la unidad de Responsabilidad Social Académica de la Facultad de Ciencias Jurídicas y Sociales.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '75',
        'institucion':'Bufete Popular de la Universidad Rafael Landívar', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':15.501792634567975,   
        'longitud':-90.36287913400592,
        'direccion':'1.ª calle 5-28 zona 8, Edificio contiguo a Casa Damasco, Cobán, Alta Verapaz',
        'email':'bufetepopular@url.edu.gt',
        'URL':'https://principal.url.edu.gt/acerca-de/servicios/bufete-popular/',
        'contacto':'+502 242 62626',
        'descripcion':'El Bufete Popular de la Universidad Rafael Landívar es el centro de prácticas y la unidad de Responsabilidad Social Académica de la Facultad de Ciencias Jurídicas y Sociales.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '76',
        'institucion':'Bufete Popular de la Universidad Rafael Landívar', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':15.322430264972983,   
        'longitud':-91.49465026138031, 
        'direccion':'6.ª calle 9-90, zona 1, Campus San Roque González, S. J. de Huehuetenango',
        'email':'bufetepopular@url.edu.gt',
        'URL':'https://principal.url.edu.gt/acerca-de/servicios/bufete-popular/',
        'contacto':'+502 242 62626',
        'descripcion':'El Bufete Popular de la Universidad Rafael Landívar es el centro de prácticas y la unidad de Responsabilidad Social Académica de la Facultad de Ciencias Jurídicas y Sociales.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },
    {
        'id': '77',
        'institucion':'Bufete Popular de la Universidad Rafael Landívar', 
        'categoria':'Orientacion y Servicios Legales', 
        'latitud':14.840397662888138,   
        'longitud':-91.52226359022649,  
        'direccion':'Calle Rodolfo Robles 19-24, zona 3, Edificio Plaza Esmeralda, tercer nivel',
        'email':'bufetepopular@url.edu.gt',
        'URL':'https://principal.url.edu.gt/acerca-de/servicios/bufete-popular/',
        'contacto':'+502 242 62626',
        'descripcion':'El Bufete Popular de la Universidad Rafael Landívar es el centro de prácticas y la unidad de Responsabilidad Social Académica de la Facultad de Ciencias Jurídicas y Sociales.',
        'rubro':'PUBLICO',
        'pais':'Guatemala',
    },



]